name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: maxim-lobanov/setup-xcode@v1.3.0
      with:
        xcode-version: 12.4
      
    - name: Bundle install
      run: bundle install
      
    - name: Build and Tests
      run: |
        set -o pipefail
        xcodebuild -project MagicImages.xcodeproj \
           -scheme MagicImages-Package \
           -destination platform=iOS\ Simulator,name=iPhone\ 8 \
           clean test | xcpretty
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.5.2
