name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and Tests
      run: xcodebuild clean build test -project MagicImages.xcodeproj -scheme "MagicImages-Package" -enableCodeCoverage YES -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
